//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sobaco.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowState {
            get {
                return ((int)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Style {
            get {
                return ((int)(this["Style"]));
            }
            set {
                this["Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AveStep {
            get {
                return ((int)(this["AveStep"]));
            }
            set {
                this["AveStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Range {
            get {
                return ((int)(this["Range"]));
            }
            set {
                this["Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CandleSize {
            get {
                return ((int)(this["CandleSize"]));
            }
            set {
                this["CandleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Scale {
            get {
                return ((int)(this["Scale"]));
            }
            set {
                this["Scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int H1 {
            get {
                return ((int)(this["H1"]));
            }
            set {
                this["H1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int H2 {
            get {
                return ((int)(this["H2"]));
            }
            set {
                this["H2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int H3 {
            get {
                return ((int)(this["H3"]));
            }
            set {
                this["H3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int H4 {
            get {
                return ((int)(this["H4"]));
            }
            set {
                this["H4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int H5 {
            get {
                return ((int)(this["H5"]));
            }
            set {
                this["H5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Tab {
            get {
                return ((int)(this["Tab"]));
            }
            set {
                this["Tab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1001")]
        public string Favorites {
            get {
                return ((string)(this["Favorites"]));
            }
            set {
                this["Favorites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OkiniiriFileName {
            get {
                return ((string)(this["OkiniiriFileName"]));
            }
            set {
                this["OkiniiriFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double Hanbun1 {
            get {
                return ((double)(this["Hanbun1"]));
            }
            set {
                this["Hanbun1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Hanbun2 {
            get {
                return ((double)(this["Hanbun2"]));
            }
            set {
                this["Hanbun2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public double Hanbun3 {
            get {
                return ((double)(this["Hanbun3"]));
            }
            set {
                this["Hanbun3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double Hanbun4 {
            get {
                return ((double)(this["Hanbun4"]));
            }
            set {
                this["Hanbun4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfArrayOfArrayOfInt xmlns:xsi=\"htt" +
            "p://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSch" +
            "ema\">\r\n  <ArrayOfArrayOfInt>\r\n    <ArrayOfInt>\r\n      <int>5</int>\r\n      <int>2" +
            "5</int>\r\n      <int>75</int>\r\n      <int>200</int>\r\n      <int>0</int>\r\n    </Ar" +
            "rayOfInt>\r\n    <ArrayOfInt>\r\n      <int>9</int>\r\n      <int>13</int>\r\n      <int" +
            ">26</int>\r\n      <int>50</int>\r\n      <int>0</int>\r\n    </ArrayOfInt>\r\n    <Arra" +
            "yOfInt>\r\n      <int>6</int>\r\n      <int>12</int>\r\n      <int>24</int>\r\n      <in" +
            "t>60</int>\r\n      <int>0</int>\r\n    </ArrayOfInt>\r\n  </ArrayOfArrayOfInt>\r\n  <Ar" +
            "rayOfArrayOfInt>\r\n    <ArrayOfInt>\r\n      <int>5</int>\r\n      <int>10</int>\r\n   " +
            "   <int>30</int>\r\n      <int>50</int>\r\n      <int>150</int>\r\n    </ArrayOfInt>\r\n" +
            "    <ArrayOfInt>\r\n      <int>5</int>\r\n      <int>10</int>\r\n      <int>30</int>\r\n" +
            "      <int>50</int>\r\n      <int>150</int>\r\n    </ArrayOfInt>\r\n    <ArrayOfInt>\r\n" +
            "      <int>5</int>\r\n      <int>10</int>\r\n      <int>30</int>\r\n      <int>50</int" +
            ">\r\n      <int>150</int>\r\n    </ArrayOfInt>\r\n  </ArrayOfArrayOfInt>\r\n  <ArrayOfAr" +
            "rayOfInt>\r\n    <ArrayOfInt>\r\n      <int>7</int>\r\n      <int>14</int>\r\n      <int" +
            ">42</int>\r\n      <int>0</int>\r\n      <int>0</int>\r\n    </ArrayOfInt>\r\n    <Array" +
            "OfInt>\r\n      <int>7</int>\r\n      <int>14</int>\r\n      <int>42</int>\r\n      <int" +
            ">0</int>\r\n      <int>0</int>\r\n    </ArrayOfInt>\r\n    <ArrayOfInt>\r\n      <int>7<" +
            "/int>\r\n      <int>14</int>\r\n      <int>42</int>\r\n      <int>0</int>\r\n      <int>" +
            "0</int>\r\n    </ArrayOfInt>\r\n  </ArrayOfArrayOfInt>\r\n</ArrayOfArrayOfArrayOfInt>")]
        public string Idouheikin {
            get {
                return ((string)(this["Idouheikin"]));
            }
            set {
                this["Idouheikin"] = value;
            }
        }
    }
}
